/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as NovaParolaRouteImport } from './routes/nova-parola'
import { Route as ObshtiUsloviyaRouteImport } from './routes/obshti-usloviya'
import { Route as PolitikaZaBiskvitkiRouteImport } from './routes/politika-za-biskvitki'
import { Route as PolitikaZaPoveritelnostRouteImport } from './routes/politika-za-poveritelnost'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SravnenieRouteImport } from './routes/sravnenie'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as ReportEkatteRouteImport } from './routes/report.$ekatte'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin_.feedback'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin_.import'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin_.reports'
import { Route as ApiDiagReportRouteImport } from './routes/api.diag.report'
import { Route as ApiDiagReportsRouteImport } from './routes/api.diag.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaParolaRoute = NovaParolaRouteImport.update({
  id: '/nova-parola',
  path: '/nova-parola',
  getParentRoute: () => rootRouteImport,
} as any)
const ObshtiUsloviyaRoute = ObshtiUsloviyaRouteImport.update({
  id: '/obshti-usloviya',
  path: '/obshti-usloviya',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaZaBiskvitkiRoute = PolitikaZaBiskvitkiRouteImport.update({
  id: '/politika-za-biskvitki',
  path: '/politika-za-biskvitki',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaZaPoveritelnostRoute = PolitikaZaPoveritelnostRouteImport.update({
  id: '/politika-za-poveritelnost',
  path: '/politika-za-poveritelnost',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SravnenieRoute = SravnenieRouteImport.update({
  id: '/sravnenie',
  path: '/sravnenie',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ReportEkatteRoute = ReportEkatteRouteImport.update({
  id: '/report/$ekatte',
  path: '/report/$ekatte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin_/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin_/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin_/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiDiagReportRoute = ApiDiagReportRouteImport.update({
  id: '/api/diag/report',
  path: '/api/diag/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagReportsRoute = ApiDiagReportsRouteImport.update({
  id: '/api/diag/reports',
  path: '/api/diag/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakti': typeof KontaktiRoute
  '/nova-parola': typeof NovaParolaRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sravnenie': typeof SravnenieRoute
  '/vhod': typeof VhodRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/report/$ekatte': typeof ReportEkatteRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/api/diag/report': typeof ApiDiagReportRoute
  '/api/diag/reports': typeof ApiDiagReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakti': typeof KontaktiRoute
  '/nova-parola': typeof NovaParolaRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sravnenie': typeof SravnenieRoute
  '/vhod': typeof VhodRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/report/$ekatte': typeof ReportEkatteRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/api/diag/report': typeof ApiDiagReportRoute
  '/api/diag/reports': typeof ApiDiagReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/kontakti': typeof KontaktiRoute
  '/nova-parola': typeof NovaParolaRoute
  '/obshti-usloviya': typeof ObshtiUsloviyaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost': typeof PolitikaZaPoveritelnostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sravnenie': typeof SravnenieRoute
  '/vhod': typeof VhodRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/report/$ekatte': typeof ReportEkatteRoute
  '/_authenticated/admin_/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin_/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin_/reports': typeof AuthenticatedAdminReportsRoute
  '/api/diag/report': typeof ApiDiagReportRoute
  '/api/diag/reports': typeof ApiDiagReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakti'
    | '/nova-parola'
    | '/obshti-usloviya'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/sravnenie'
    | '/vhod'
    | '/admin'
    | '/profil'
    | '/report/$ekatte'
    | '/admin/feedback'
    | '/admin/import'
    | '/admin/reports'
    | '/api/diag/report'
    | '/api/diag/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakti'
    | '/nova-parola'
    | '/obshti-usloviya'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/sravnenie'
    | '/vhod'
    | '/admin'
    | '/profil'
    | '/report/$ekatte'
    | '/admin/feedback'
    | '/admin/import'
    | '/admin/reports'
    | '/api/diag/report'
    | '/api/diag/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kontakti'
    | '/nova-parola'
    | '/obshti-usloviya'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost'
    | '/sitemap.xml'
    | '/sravnenie'
    | '/vhod'
    | '/_authenticated/admin'
    | '/_authenticated/profil'
    | '/report/$ekatte'
    | '/_authenticated/admin_/feedback'
    | '/_authenticated/admin_/import'
    | '/_authenticated/admin_/reports'
    | '/api/diag/report'
    | '/api/diag/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  KontaktiRoute: typeof KontaktiRoute
  NovaParolaRoute: typeof NovaParolaRoute
  ObshtiUsloviyaRoute: typeof ObshtiUsloviyaRoute
  PolitikaZaBiskvitkiRoute: typeof PolitikaZaBiskvitkiRoute
  PolitikaZaPoveritelnostRoute: typeof PolitikaZaPoveritelnostRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SravnenieRoute: typeof SravnenieRoute
  VhodRoute: typeof VhodRoute
  ReportEkatteRoute: typeof ReportEkatteRoute
  ApiDiagReportRoute: typeof ApiDiagReportRoute
  ApiDiagReportsRoute: typeof ApiDiagReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-parola': {
      id: '/nova-parola'
      path: '/nova-parola'
      fullPath: '/nova-parola'
      preLoaderRoute: typeof NovaParolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obshti-usloviya': {
      id: '/obshti-usloviya'
      path: '/obshti-usloviya'
      fullPath: '/obshti-usloviya'
      preLoaderRoute: typeof ObshtiUsloviyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-za-biskvitki': {
      id: '/politika-za-biskvitki'
      path: '/politika-za-biskvitki'
      fullPath: '/politika-za-biskvitki'
      preLoaderRoute: typeof PolitikaZaBiskvitkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-za-poveritelnost': {
      id: '/politika-za-poveritelnost'
      path: '/politika-za-poveritelnost'
      fullPath: '/politika-za-poveritelnost'
      preLoaderRoute: typeof PolitikaZaPoveritelnostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sravnenie': {
      id: '/sravnenie'
      path: '/sravnenie'
      fullPath: '/sravnenie'
      preLoaderRoute: typeof SravnenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/report/$ekatte': {
      id: '/report/$ekatte'
      path: '/report/$ekatte'
      fullPath: '/report/$ekatte'
      preLoaderRoute: typeof ReportEkatteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/feedback': {
      id: '/_authenticated/admin_/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/import': {
      id: '/_authenticated/admin_/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/reports': {
      id: '/_authenticated/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/diag/report': {
      id: '/api/diag/report'
      path: '/api/diag/report'
      fullPath: '/api/diag/report'
      preLoaderRoute: typeof ApiDiagReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/reports': {
      id: '/api/diag/reports'
      path: '/api/diag/reports'
      fullPath: '/api/diag/reports'
      preLoaderRoute: typeof ApiDiagReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  KontaktiRoute: KontaktiRoute,
  NovaParolaRoute: NovaParolaRoute,
  ObshtiUsloviyaRoute: ObshtiUsloviyaRoute,
  PolitikaZaBiskvitkiRoute: PolitikaZaBiskvitkiRoute,
  PolitikaZaPoveritelnostRoute: PolitikaZaPoveritelnostRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SravnenieRoute: SravnenieRoute,
  VhodRoute: VhodRoute,
  ReportEkatteRoute: ReportEkatteRoute,
  ApiDiagReportRoute: ApiDiagReportRoute,
  ApiDiagReportsRoute: ApiDiagReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
